/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as FormIndexImport } from './routes/form/index'

// Create Virtual Routes

const ResultIdLazyImport = createFileRoute('/result/$id')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FormIndexRoute = FormIndexImport.update({
  id: '/form/',
  path: '/form/',
  getParentRoute: () => rootRoute,
} as any)

const ResultIdLazyRoute = ResultIdLazyImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/result/$id.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/result/$id': {
      id: '/result/$id'
      path: '/result/$id'
      fullPath: '/result/$id'
      preLoaderRoute: typeof ResultIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/form/': {
      id: '/form/'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/result/$id': typeof ResultIdLazyRoute
  '/form': typeof FormIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/result/$id': typeof ResultIdLazyRoute
  '/form': typeof FormIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/result/$id': typeof ResultIdLazyRoute
  '/form/': typeof FormIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/result/$id' | '/form'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/result/$id' | '/form'
  id: '__root__' | '/' | '/result/$id' | '/form/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResultIdLazyRoute: typeof ResultIdLazyRoute
  FormIndexRoute: typeof FormIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResultIdLazyRoute: ResultIdLazyRoute,
  FormIndexRoute: FormIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/result/$id",
        "/form/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/result/$id": {
      "filePath": "result/$id.lazy.tsx"
    },
    "/form/": {
      "filePath": "form/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
