/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as FormIndexImport } from './routes/form/index'

// Create Virtual Routes

const ResultIdIndexLazyImport = createFileRoute('/result/$id/')()
const ResultIdDetailLazyImport = createFileRoute('/result/$id/detail')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FormIndexRoute = FormIndexImport.update({
  id: '/form/',
  path: '/form/',
  getParentRoute: () => rootRoute,
} as any)

const ResultIdIndexLazyRoute = ResultIdIndexLazyImport.update({
  id: '/result/$id/',
  path: '/result/$id/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/result/$id/index.lazy').then((d) => d.Route),
)

const ResultIdDetailLazyRoute = ResultIdDetailLazyImport.update({
  id: '/result/$id/detail',
  path: '/result/$id/detail',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/result/$id/detail.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/form/': {
      id: '/form/'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormIndexImport
      parentRoute: typeof rootRoute
    }
    '/result/$id/detail': {
      id: '/result/$id/detail'
      path: '/result/$id/detail'
      fullPath: '/result/$id/detail'
      preLoaderRoute: typeof ResultIdDetailLazyImport
      parentRoute: typeof rootRoute
    }
    '/result/$id/': {
      id: '/result/$id/'
      path: '/result/$id'
      fullPath: '/result/$id'
      preLoaderRoute: typeof ResultIdIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/form': typeof FormIndexRoute
  '/result/$id/detail': typeof ResultIdDetailLazyRoute
  '/result/$id': typeof ResultIdIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/form': typeof FormIndexRoute
  '/result/$id/detail': typeof ResultIdDetailLazyRoute
  '/result/$id': typeof ResultIdIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/form/': typeof FormIndexRoute
  '/result/$id/detail': typeof ResultIdDetailLazyRoute
  '/result/$id/': typeof ResultIdIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/form' | '/result/$id/detail' | '/result/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/form' | '/result/$id/detail' | '/result/$id'
  id: '__root__' | '/' | '/form/' | '/result/$id/detail' | '/result/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormIndexRoute: typeof FormIndexRoute
  ResultIdDetailLazyRoute: typeof ResultIdDetailLazyRoute
  ResultIdIndexLazyRoute: typeof ResultIdIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormIndexRoute: FormIndexRoute,
  ResultIdDetailLazyRoute: ResultIdDetailLazyRoute,
  ResultIdIndexLazyRoute: ResultIdIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/form/",
        "/result/$id/detail",
        "/result/$id/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/form/": {
      "filePath": "form/index.tsx"
    },
    "/result/$id/detail": {
      "filePath": "result/$id/detail.lazy.tsx"
    },
    "/result/$id/": {
      "filePath": "result/$id/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
